name: Update Version in DESCRIPTION

on:
  push:
    branches:
      - main

env:
  BUMP_VERSION: true

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if branch version_bump already exists
        run: |
          if git ls-remote --heads origin | grep -q "refs/heads/version_bump"; then
            echo "Branch version_bump already exists. Skipping this job. Please merge the existing branch first."
            echo "BUMP_VERSION=false" >> $GITHUB_ENV
          fi
          BUMP_VERSION

      - name: Get current version number
        id: get-version
        if: env.UPDATE_VERSION == 'true'
        run: |
          current_version=$(grep "Version:" DESCRIPTION | sed 's/Version: \([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)/\1.\2.\3/')
          echo "::set-output name=version::$current_version"

      - name: Increment version number
        id: increment-version
        if: env.UPDATE_VERSION == 'true'
        run: |
          current_version=${{ steps.get-version.outputs.version }}
          major=$(echo $current_version | cut -d '.' -f 1)
          minor=$(echo $current_version | cut -d '.' -f 2)
          patch=$(echo $current_version | cut -d '.' -f 3)
          new_version="$major.$minor.$((patch+1))"
          echo "::set-output name=new_version::$new_version"

      - name: Update DESCRIPTION file
        if: env.UPDATE_VERSION == 'true'
        run: |
         sed -i "s/Version:.*$/Version: ${{ steps.increment-version.outputs.new_version }}/g" DESCRIPTION
       
      - name: Create pull request
        if: env.UPDATE_VERSION == 'true'
        # https://stackoverflow.com/questions/68057744/create-pull-request-with-github-action
        run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         
         # create new branch
         git branch bump_version
         git checkout bump_version
         
         # Add the changes and commit
         git add DESCRIPTION
         
         git commit -m "Bump version number in DESCRIPTION"
         
         git push --set-upstream origin bump_version

         # Request merge
         gh pr create -B main -H bump_version --title 'Bump version' --body 'Created by Github action'
       
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
